stages:
  - test

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:4567"
  DOCKER_DRIVER: overlay2

test:
  stage: test
  image: hseeberger/scala-sbt:8u222_1.3.3_2.13.1
  script:
    - sbt clean test