stages:
  - test
  - build

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2

test:
  stage: test
  image: hseeberger/scala-sbt:8u222_1.3.3_2.13.1
  script:
    - sbt clean testOnly *.ProofSuite *.OpsSuite *.DidParserSuite
  cache:
    paths:
      - ~/.ivy2

dockerize:
  stage: build
  image: hseeberger/scala-sbt:8u222_1.3.3_2.13.1
  script:
    - sbt docker:publishLocal
