name: Test

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    container: hseeberger/scala-sbt:8u222_1.3.3_2.13.1
    steps:
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.ivy2
      - run: sbt clean testOnly *.ProofSuite *.OpsSuite *.DidParserSuite
